import './style.css';
import { LocalRepository } from './database.js';

const $ = (s, root=document) => root.querySelector(s);
const uid = () => globalThis.crypto?.randomUUID?.() || `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const today = () => new Date().toISOString().slice(0,10);
const formatDate = d => new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(d+'T12:00:00'));
const kg = n => `${Number(n||0).toLocaleString()} kg`;
const e1rm = (w,r) => Math.round(w * (1+r/30));

const library = [
 ['Incline Dumbbell Press','Chest','Dumbbells'],['Machine Chest Press','Chest','Machine'],['Cable Lateral Raise','Shoulders','Cable'],['Overhead Rope Extension','Triceps','Cable'],['Lat Pulldown','Back','Cable'],['Chest Supported Row','Back','Machine'],['Reverse Pec Deck','Shoulders','Machine'],['Incline Dumbbell Curl','Biceps','Dumbbells'],['Romanian Deadlift','Hamstrings','Barbell'],['Leg Press','Quads','Machine'],['Leg Curl','Hamstrings','Machine'],['Standing Calf Raise','Calves','Machine'],['Barbell Bench Press','Chest','Barbell'],['Seated Cable Row','Back','Cable'],['Leg Extension','Quads','Machine'],['Cable Crunch','Abs','Cable']
].map(([name,muscle,equipment])=>({id:name.toLowerCase().replaceAll(' ','-'),name,muscle,equipment,secondary:[],type:'Resistance',instructions:`Set up with a stable position. Control each repetition through a full comfortable range of motion.`,favorite:false,custom:false}));
const templates = {
 Push:[['incline-dumbbell-press','3','8–12','1–2',120],['machine-chest-press','3','8–12','1–2',90],['cable-lateral-raise','3','12–15','1–2',60],['overhead-rope-extension','3','10–15','1–2',75]],
 Pull:[['lat-pulldown','3','8–12','1–2',90],['chest-supported-row','3','8–12','1–2',90],['reverse-pec-deck','3','12–15','1–2',60],['incline-dumbbell-curl','3','10–15','1–2',75]],
 Legs:[['romanian-deadlift','3','6–10','1–2',120],['leg-press','3','10–15','1–2',120],['leg-curl','3','10–15','1–2',75],['standing-calf-raise','3','10–15','1–2',60]],
 Upper:[['barbell-bench-press','3','6–10','1–2',120],['seated-cable-row','3','8–12','1–2',90],['cable-lateral-raise','3','12–15','1–2',60],['incline-dumbbell-curl','2','10–15','1–2',75]]
};
function makeProgram(){const weeks=Array.from({length:12},(_,i)=>({number:i+1,days:['Push','Pull','Rest','Legs','Upper','Rest','Rest'].map((name,index)=>({id:`w${i+1}d${index+1}`,day:index+1,name,rest:name==='Rest',exercises:(templates[name]||[]).map(([exerciseId,sets,reps,rir,rest])=>({id:uid(),exerciseId,sets:+sets,reps,rir,rest}))}))}));return {id:'hypertrophy-12',name:'12 Week Hypertrophy',description:'A measured four-day split for building size, strength, and confidence.',author:'Form Studio',duration:'12 weeks',numberOfWeeks:12,goal:'Muscle hypertrophy',difficulty:'Advanced',equipment:'Full gym',createdAt:today(),updatedAt:today(),weeks};}
function seed(){const p=makeProgram(), date=n=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)}; const past=[['Push',2],['Pull',4],['Legs',7],['Upper',9]].map(([name,ago],i)=>({id:uid(),name,date:date(ago),startedAt:new Date(date(ago)).toISOString(),finishedAt:new Date(Date.now()-ago*864e5+42*6e4).toISOString(),programDayId:null,notes:'',exercises:(templates[name]||[]).map(([exerciseId,sets],j)=>({id:uid(),exerciseId,notes:'',sets:Array.from({length:sets},(_,x)=>({id:uid(),weight:25+i*2.5+j*2.5,reps:10+x%2,rir:2,completed:true,notes:''}))}))}));return {schemaVersion:1,programs:[p],library,workouts:past,active:null,settings:{theme:'dark'},body:[]};}
const store=new LocalRepository(); let state; let deferredInstall; let page='home'; let selectedWeek=1; let timer=null; let timerEnd=0; let storageIssue=''; let saveQueue=Promise.resolve();
const allSets=w=>w.exercises.flatMap(x=>x.sets.filter(s=>s.completed)); const volume=w=>allSets(w).reduce((a,s)=>a+s.weight*s.reps,0); const duration=w=>w.finishedAt?Math.max(1,Math.round((new Date(w.finishedAt)-new Date(w.startedAt))/60000)):0;
const exName=id=>state.library.find(x=>x.id===id)?.name||'Custom exercise'; const exInfo=id=>state.library.find(x=>x.id===id)||{};
function lastPerformance(id){return state.workouts.filter(w=>w.finishedAt).sort((a,b)=>b.finishedAt.localeCompare(a.finishedAt)).flatMap(w=>w.exercises).find(e=>e.exerciseId===id)?.sets.filter(s=>s.completed)||[]}
function currentProgram(){return state.programs[0]}
function scheduled(){const p=currentProgram(), d=new Date().getDay(), i=(d+6)%7; return p.weeks[0].days[i].rest?p.weeks[0].days.find(x=>!x.rest):p.weeks[0].days[i]}
function save(){
  if (storageIssue) return Promise.resolve();
  // Serialising writes prevents rapid mobile input events from persisting an older snapshot last.
  saveQueue = saveQueue.catch(() => {}).then(() => store.write(state));
  return saveQueue.catch(error => { storageIssue='Local storage became unavailable. Export and restore your backup after re-enabling device storage.'; console.error('Unable to save training data', error); });
}
function nav(){return `<nav class="bottom-nav">${[['home','⌂','Home'],['program','◫','Program'],['workout','◉','Workout'],['history','◷','History'],['progress','↗','Progress']].map(([p,i,l])=>`<button data-page="${p}" class="${page===p?'active':''}" aria-label="${l}"><b>${i}</b><span>${l}</span></button>`).join('')}</nav>`}
function render(){document.documentElement.dataset.theme=state.settings.theme==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):state.settings.theme; $('#app').innerHTML=`<main>${page==='home'?home():page==='program'?program():page==='workout'?workout():page==='history'?history():progress()}</main>${nav()}<div id="modal"></div>`; bind();}
function home(){const s=scheduled(), done=state.workouts.filter(w=>w.date>=weekStart()).length, prs=records().slice(0,2), latest=state.workouts.filter(w=>w.finishedAt).slice(0,3);return `${storageIssue?`<aside class="storage-warning"><b>Storage unavailable</b><span>${storageIssue}</span></aside>`:''}<header><div><p class="eyebrow">TRAIN WITH INTENT</p><h1>Good morning, Alex</h1></div><button class="avatar" data-action="settings" aria-label="Settings">A</button></header><section class="hero"><p class="eyebrow accent">TODAY'S SESSION</p><h2>${s.name}</h2><p>Week 1 · Day ${s.day} <i>•</i> ${s.exercises.length} exercises <i>•</i> ${s.exercises.reduce((a,x)=>a+x.sets,0)} sets</p><button class="primary wide" data-action="start-today">Start today’s workout <span>→</span></button><button class="text-button" data-action="free">＋ Start a free workout</button></section><section class="stat-row"><div><small>THIS WEEK</small><strong>${done}<em>/4</em></strong><span>sessions</span></div><div><small>STREAK</small><strong>${streak()}</strong><span>days active</span></div><div><small>VOLUME</small><strong>${Math.round(state.workouts.filter(w=>w.date>=weekStart()).reduce((a,w)=>a+volume(w),0)/100)/10}<em>k</em></strong><span>kg moved</span></div></section><section><div class="section-title"><h3>Training week</h3><button data-page="program">View program</button></div><div class="week-dots">${currentProgram().weeks[0].days.map(d=>`<div class="${d.rest?'rest':state.workouts.some(w=>w.programDayId===d.id)?'complete':''}"><small>${['M','T','W','T','F','S','S'][d.day-1]}</small><b>${d.rest?'—':d.name.slice(0,1)}</b></div>`).join('')}</div></section><section><div class="section-title"><h3>Recent records</h3><button data-page="progress">See all</button></div>${prs.length?prs.map(r=>`<article class="record"><span>✦</span><div><b>${r.name}</b><small>${r.weight} kg × ${r.reps} · estimated 1RM ${r.erm} kg</small></div><time>${formatDate(r.date)}</time></article>`).join(''):'<p class="muted">Complete a session to start building your records.</p>'}</section><section><div class="section-title"><h3>Recent activity</h3><button data-page="history">History</button></div>${latest.map(w=>`<article class="activity"><span class="check">✓</span><div><b>${w.name}</b><small>${formatDate(w.date)} · ${duration(w)} min · ${kg(volume(w))}</small></div></article>`).join('')}</section>`}
function program(){const p=currentProgram(), week=p.weeks[selectedWeek-1], completed=state.workouts.filter(w=>w.finishedAt).length;return `<header><div><p class="eyebrow">ACTIVE PROGRAM</p><h1>${p.name}</h1></div><button class="icon" data-action="edit-program">⋯</button></header><section class="program-card"><p>${p.description}</p><div class="tags"><span>${p.goal}</span><span>${p.difficulty}</span><span>${p.equipment}</span></div><div class="progress-label"><b>Week ${selectedWeek} of ${p.numberOfWeeks}</b><span>${Math.min(100,Math.round(completed/(p.numberOfWeeks*4)*100))}% complete</span></div><div class="bar"><i style="width:${Math.min(100,completed/(p.numberOfWeeks*4)*100)}%"></i></div></section><div class="week-selector">${p.weeks.map(w=>`<button data-week="${w.number}" class="${w.number===selectedWeek?'selected':''}"><small>WEEK</small><b>${w.number}</b></button>`).join('')}</div><section><p class="eyebrow">WEEK ${selectedWeek} · BUILD</p><div class="day-list">${week.days.map(d=>`<button class="day ${d.rest?'rest':''} ${state.workouts.some(w=>w.programDayId===d.id)?'completed':''}" data-action="${d.rest?'none':'start-day'}" data-day="${d.id}"><span>${['MON','TUE','WED','THU','FRI','SAT','SUN'][d.day-1]}</span><div><b>${d.name}</b><small>${d.rest?'Recovery and movement':`${d.exercises.length} exercises · ${d.exercises.reduce((a,x)=>a+x.sets,0)} sets`}</small></div><i>${d.rest?'Rest':state.workouts.some(w=>w.programDayId===d.id)?'✓':'→'}</i></button>`).join('')}</div></section>`}
function exerciseCard(e,index){const info=exInfo(e.exerciseId), previous=lastPerformance(e.exerciseId), target=`${e.sets} × ${e.reps} · RIR ${e.rir}`;return `<article class="exercise-card"><div class="exercise-head"><div><small>${info.muscle||'Other'} · ${info.equipment||'Custom'}</small><h3>${exName(e.exerciseId)}</h3><p>${target} <i>•</i> Rest ${e.rest||90}s</p></div><button class="dots" data-action="exercise-notes" data-exercise="${e.id}" aria-label="Exercise options">⋯</button></div>${previous.length?`<div class="last"><b>LAST TIME</b><span>${previous.map(s=>`${s.weight} kg × ${s.reps} <em>RIR ${s.rir}</em>`).join(' · ')}</span><button data-action="copy-last" data-exercise="${e.id}">Copy last session</button></div>`:''}<div class="set-grid header-row"><small>SET</small><small>KG</small><small>REPS <em>${e.reps}</em></small><small>RIR</small><small>DONE</small></div>${e.sets.map((s,i)=>`<div class="set-grid"><b>${i+1}</b><input aria-label="Set ${i+1} weight" inputmode="decimal" type="number" value="${s.weight||''}" data-field="weight" data-exercise="${e.id}" data-set="${s.id}" placeholder="—"><input aria-label="Set ${i+1} reps" inputmode="numeric" type="number" value="${s.reps||''}" data-field="reps" data-exercise="${e.id}" data-set="${s.id}" placeholder="—"><button class="rir" data-action="rir" data-exercise="${e.id}" data-set="${s.id}">${s.rir??2}</button><button class="complete ${s.completed?'on':''}" data-action="complete-set" data-exercise="${e.id}" data-set="${s.id}" aria-label="Complete set ${i+1}">✓</button></div>`).join('')}<button class="add-set" data-action="add-set" data-exercise="${e.id}">＋ Add set</button></article>`}
function workout(){if(!state.active)return `<header><div><p class="eyebrow">TRAINING</p><h1>Ready when you are</h1></div></header><section class="empty"><span>◉</span><h2>No active workout</h2><p>Start your scheduled session or build a free workout around what feels good today.</p><button class="primary wide" data-action="start-today">Start today’s workout</button><button class="secondary wide" data-action="free">Start free workout</button></section>`;const w=state.active, completed=allSets(w).length, total=w.exercises.reduce((a,e)=>a+e.sets.length,0);return `<header class="workout-header"><button class="back" data-page="home">‹</button><div><p class="eyebrow">${w.programDayId?'WEEK 1 · PROGRAM':'FREE WORKOUT'}</p><h1>${w.name}</h1></div><strong id="clock">${elapsed()}</strong></header><div class="workout-progress"><span>${completed} / ${total} sets complete</span><div class="bar"><i style="width:${total?completed/total*100:0}%"></i></div></div>${timerEnd?`<aside class="timer"><b>REST</b><strong id="timer-count">${timerText()}</strong><button data-action="stop-timer">×</button></aside>`:''}<div class="workout-actions"><button class="secondary" data-action="add-exercise">＋ Add exercise</button><button class="primary" data-action="finish">Finish workout</button></div><div class="exercises">${w.exercises.map(exerciseCard).join('')}</div><label class="notes-label">WORKOUT NOTES<textarea data-action="workout-notes" placeholder="How did this session feel?">${w.notes||''}</textarea></label>`}
function history(){const ws=state.workouts.filter(w=>w.finishedAt).sort((a,b)=>b.date.localeCompare(a.date));return `<header><div><p class="eyebrow">TRAINING LOG</p><h1>History</h1></div><button class="icon" data-action="backup" aria-label="Backup data">⇧</button></header><section class="calendar"><div class="section-title"><h3>${new Intl.DateTimeFormat('en',{month:'long',year:'numeric'}).format(new Date())}</h3><span> ${ws.length} workouts</span></div><div class="calendar-grid">${['M','T','W','T','F','S','S'].map(x=>`<small>${x}</small>`).join('')}${Array.from({length:30},(_,i)=>{let date=new Date();date.setDate(30-i);let d=date.toISOString().slice(0,10),w=ws.find(x=>x.date===d);return `<button class="${w?'logged':''}" data-action="open-history" data-workout="${w?.id||''}">${date.getDate()}${w?'<i>•</i>':''}</button>`}).join('')}</div></section><section><div class="section-title"><h3>Recent workouts</h3><span>${ws.length} total</span></div>${ws.map(w=>`<button class="history-row" data-action="open-history" data-workout="${w.id}"><span class="check">✓</span><div><b>${w.name}</b><small>${formatDate(w.date)} · ${duration(w)} min · ${w.exercises.length} exercises</small></div><strong>${kg(volume(w))}</strong></button>`).join('')||'<p class="muted">Your completed workouts will appear here.</p>'}</section>`}
function progress(){const ws=state.workouts.filter(w=>w.finishedAt), sets=ws.flatMap(allSets), muscle=Object.entries(sets.reduce((a,s)=>{const e=ws.flatMap(w=>w.exercises).find(x=>x.sets.includes(s));const m=exInfo(e?.exerciseId).muscle||'Other';a[m]=(a[m]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]);return `<header><div><p class="eyebrow">YOUR PROGRESS</p><h1>Performance</h1></div><button class="icon" data-action="body">＋</button></header><div class="periods"><button class="selected">30 days</button><button>90 days</button><button>All time</button></div><section class="metrics"><div><small>WORKOUTS</small><strong>${ws.length}</strong><span>all time</span></div><div><small>AVG RIR</small><strong>${sets.length?(sets.reduce((a,s)=>a+Number(s.rir||0),0)/sets.length).toFixed(1):'—'}</strong><span>completed sets</span></div><div><small>VOLUME</small><strong>${Math.round(ws.reduce((a,w)=>a+volume(w),0)/1000)}k</strong><span>kg moved</span></div></section><section><div class="section-title"><h3>Personal records</h3><span>Best sets</span></div>${records().map(r=>`<article class="record"><span>✦</span><div><b>${r.name}</b><small>${r.weight} kg × ${r.reps} · est. 1RM ${r.erm} kg</small></div><time>${formatDate(r.date)}</time></article>`).join('')||'<p class="muted">Complete sets to unlock records.</p>'}</section><section><div class="section-title"><h3>Muscle volume</h3><span>sets</span></div><div class="muscles">${muscle.map(([m,n])=>`<div><div><b>${m}</b><span>${n} sets</span></div><i style="width:${Math.min(100,n/16*100)}%"></i></div>`).join('')||'<p class="muted">Your muscle volume will build here.</p>'}</div></section><section><div class="section-title"><h3>Body metrics</h3><button data-action="body">Add check-in</button></div>${state.body.length?state.body.slice(-2).reverse().map(x=>`<article class="activity"><span>◌</span><div><b>${x.weight} kg</b><small>${formatDate(x.date)}${x.fat?` · ${x.fat}% body fat`:''}</small></div></article>`).join(''):'<p class="muted">Optional check-ins help you connect training to outcomes.</p>'}</section>`}
function records(){const best={};state.workouts.filter(w=>w.finishedAt).forEach(w=>w.exercises.forEach(e=>e.sets.filter(s=>s.completed).forEach(s=>{const name=exName(e.exerciseId),erm=e1rm(s.weight,s.reps);if(!best[e.exerciseId]||erm>best[e.exerciseId].erm)best[e.exerciseId]={name,weight:s.weight,reps:s.reps,erm,date:w.date}})));return Object.values(best).sort((a,b)=>b.erm-a.erm)}
function weekStart(){let d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10)}function streak(){const ds=new Set(state.workouts.filter(w=>w.finishedAt).map(w=>w.date));let d=new Date(),n=0;while(ds.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function elapsed(){if(!state.active)return '0:00';let n=Math.floor((Date.now()-new Date(state.active.startedAt))/1000),m=Math.floor(n/60);return `${m}:${String(n%60).padStart(2,'0')}`}function timerText(){let n=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{selectedWeek=+b.dataset.week;render()});document.querySelectorAll('[data-field]').forEach(i=>i.oninput=()=>updateSet(i));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=e=>action(b.dataset.action,b,e));if(state.active){clearInterval(window.clk);window.clk=setInterval(()=>{const c=$('#clock');if(c)c.textContent=elapsed();const t=$('#timer-count');if(t){t.textContent=timerText();if(Date.now()>=timerEnd){timerEnd=0;render()}}},1000)}}
function updateSet(i){const e=state.active.exercises.find(x=>x.id===i.dataset.exercise),s=e.sets.find(x=>x.id===i.dataset.set);s[i.dataset.field]=+i.value;save()}
function action(a,b,e){if(a==='none')return;if(a==='start-today')startFromDay(scheduled());if(a==='start-day')startFromDay(currentProgram().weeks.flatMap(w=>w.days).find(x=>x.id===b.dataset.day));if(a==='free')freeWorkout();if(a==='complete-set'){const s=findSet(b);s.completed=!s.completed;if(s.completed)startTimer(90);save();render()}if(a==='rir'){const s=findSet(b);s.rir=s.rir===5?0:s.rir+1;save();render()}if(a==='add-set'){const x=state.active.exercises.find(x=>x.id===b.dataset.exercise);x.sets.push({id:uid(),weight:'',reps:'',rir:2,completed:false,notes:''});save();render()}if(a==='copy-last'){const x=state.active.exercises.find(x=>x.id===b.dataset.exercise),last=lastPerformance(x.exerciseId);if(last.length)x.sets=last.map(s=>({...s,id:uid(),completed:false}));save();render()}if(a==='finish')finish();if(a==='add-exercise')exercisePicker();if(a==='exercise-notes')notesModal(b.dataset.exercise);if(a==='workout-notes'){state.active.notes=e.target.value;save()}if(a==='stop-timer'){timerEnd=0;render()}if(a==='settings')settings();if(a==='backup')backup();if(a==='open-history'&&b.dataset.workout)historyDetail(b.dataset.workout);if(a==='edit-program')editProgram();if(a==='body')bodyModal()}
function findSet(b){const x=state.active.exercises.find(x=>x.id===b.dataset.exercise);return x.sets.find(x=>x.id===b.dataset.set)}
function startFromDay(d){state.active={id:uid(),name:d.name,date:today(),startedAt:new Date().toISOString(),finishedAt:null,programDayId:d.id,notes:'',exercises:d.exercises.map(x=>({...x,id:uid(),notes:'',sets:Array.from({length:x.sets},()=>({id:uid(),weight:'',reps:'',rir:2,completed:false,notes:''}))}))};page='workout';save();render()}
function freeWorkout(){state.active={id:uid(),name:'Free workout',date:today(),startedAt:new Date().toISOString(),finishedAt:null,programDayId:null,notes:'',exercises:[]};page='workout';save();render();exercisePicker()}
function startTimer(n){timerEnd=Date.now()+n*1000}function finish(){if(!allSets(state.active).length)return modal(`<h2>Log a set first</h2><p>Complete at least one set before finishing your workout.</p><button class="primary wide" data-close>Keep training</button>`);const w={...state.active,finishedAt:new Date().toISOString()};state.workouts.unshift(w);state.active=null;save();page='history';render();modal(`<div class="celebrate">✦</div><p class="eyebrow accent">WORKOUT COMPLETE</p><h2>${w.name}</h2><p>${duration(w)} min · ${w.exercises.length} exercises · ${allSets(w).length} sets</p><div class="completion-volume">${kg(volume(w))}<small>TRAINING VOLUME</small></div><button class="primary wide" data-close>View your history</button>`)}
function modal(html){const m=$('#modal');m.innerHTML=`<div class="scrim"></div><section class="modal">${html}</section>`;$('.scrim',m).onclick=closeModal;m.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal)}function closeModal(){$('#modal').innerHTML=''}
function exercisePicker(){modal(`<div class="modal-head"><div><p class="eyebrow">EXERCISE LIBRARY</p><h2>Add exercise</h2></div><button data-close>×</button></div><input class="search" placeholder="Search exercises" aria-label="Search exercises"><div class="picker-list">${state.library.map(x=>`<button data-add="${x.id}"><span>${x.muscle.slice(0,1)}</span><div><b>${x.name}</b><small>${x.muscle} · ${x.equipment}</small></div><i>＋</i></button>`).join('')}</div><button class="secondary wide" data-action="custom">＋ Create custom exercise</button>`);$('.search').oninput=e=>document.querySelectorAll('[data-add]').forEach(x=>x.parentElement.hidden=!x.textContent.toLowerCase().includes(e.target.value.toLowerCase()));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{state.active.exercises.push({id:uid(),exerciseId:b.dataset.add,sets:[{id:uid(),weight:'',reps:'',rir:2,completed:false,notes:''}],reps:'8–12',rir:'1–2',rest:90,notes:''});save();closeModal();render()});$('[data-action="custom"]').onclick=()=>customExercise()}
function customExercise(){modal(`<h2>Custom exercise</h2><label>Name<input id="custom-name" placeholder="e.g. Cable fly"></label><label>Primary muscle<select id="custom-muscle">${['Chest','Back','Shoulders','Biceps','Triceps','Quads','Hamstrings','Glutes','Calves','Abs','Other'].map(x=>`<option>${x}</option>`)}</select></label><button class="primary wide" id="create-custom">Create & add</button>`);$('#create-custom').onclick=()=>{const name=$('#custom-name').value.trim();if(!name)return;const x={id:uid(),name,muscle:$('#custom-muscle').value,equipment:'Custom',secondary:[],type:'Resistance',instructions:'',custom:true};state.library.push(x);state.active.exercises.push({id:uid(),exerciseId:x.id,sets:[{id:uid(),weight:'',reps:'',rir:2,completed:false}],reps:'8–12',rir:'1–2',rest:90});save();closeModal();render()}}
function notesModal(id){const x=state.active.exercises.find(x=>x.id===id);modal(`<h2>${exName(x.exerciseId)}</h2><label>Exercise notes<textarea id="exercise-note" placeholder="Machine settings, cues, or how it felt">${x.notes||''}</textarea></label><div class="timer-presets"><b>REST TIMER</b>${[30,60,90,120,180].map(n=>`<button data-rest="${n}">${n}s</button>`).join('')}</div><button class="primary wide" id="save-note">Save notes</button>`);$('#save-note').onclick=()=>{x.notes=$('#exercise-note').value;save();closeModal()};document.querySelectorAll('[data-rest]').forEach(b=>b.onclick=()=>{startTimer(+b.dataset.rest);closeModal();render()})}
function isInstalled(){ return window.matchMedia?.('(display-mode: standalone)').matches || navigator.standalone===true; }
function installHelp(){
  if(isInstalled()) return '<p class="installed-note">Installed app · your data stays on this device.</p>';
  const iphone=/iPhone|iPad|iPod/i.test(navigator.userAgent), android=/Android/i.test(navigator.userAgent);
  if(iphone) return '<section class="install-help"><b>Install on iPhone or iPad</b><p>In Safari, tap Share, then choose <b>Add to Home Screen</b>.</p></section>';
  if(android) return `<section class="install-help"><b>Install on Android</b><p>Use Chrome’s menu and choose <b>Install app</b> or <b>Add to Home screen</b>.</p>${deferredInstall?'<button class="secondary wide" id="install">Install app</button>':''}</section>`;
  return `<section class="install-help"><b>Install Form</b><p>Use your browser’s install option to open Form in its own window.</p>${deferredInstall?'<button class="secondary wide" id="install">Install app</button>':''}</section>`;
}
function settings(){modal(`${storageIssue?`<aside class="storage-warning"><b>Storage unavailable</b><span>${storageIssue}</span></aside>`:''}<div class="modal-head"><div><p class="eyebrow">PRIVATE BY DESIGN</p><h2>Settings</h2></div><button data-close>×</button></div><p>Your training data lives on this device. Export it anytime.</p><label>Appearance<select id="theme"><option value="dark">Dark</option><option value="light">Light</option><option value="system">System</option></select></label><button class="secondary wide" id="export">Export all data</button><label class="import">Import backup<input type="file" accept="application/json,.json" id="import"></label>${installHelp()}`);$('#theme').value=state.settings.theme;$('#theme').onchange=e=>{state.settings.theme=e.target.value;save();render();settings()};$('#export').onclick=backup;$('#import').onchange=importBackup;const install=$('#install');if(install)install.onclick=async()=>{deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;settings()}}

const BACKUP_APP = 'Form Training';
function backupPayload(){ return {appName:BACKUP_APP,schemaVersion:1,applicationVersion:'1.0.0',exportedAt:new Date().toISOString(),data:state}; }
async function backup(){
  const fileName=`WorkoutTracker_Backup_${today()}.json`, blob=new Blob([JSON.stringify(backupPayload(),null,2)],{type:'application/json'});
  const file=typeof File==='function'?new File([blob],fileName,{type:'application/json'}):null;
  try { if(file && navigator.share && (!navigator.canShare || navigator.canShare({files:[file]}))){ await navigator.share({title:'Form Training backup',text:'Local training backup',files:[file]}); return; } } catch(error) { if(error.name==='AbortError') return; }
  const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=fileName; link.click(); setTimeout(()=>URL.revokeObjectURL(link.href),1000);
}
function validateBackup(backup){
  const data=backup?.data;
  if(!backup || backup.appName!==BACKUP_APP || backup.schemaVersion!==1 || !backup.exportedAt || !data || !Array.isArray(data.programs) || !Array.isArray(data.workouts) || !Array.isArray(data.library) || !Array.isArray(data.body)) throw Error('Unsupported backup');
  if(!data.workouts.every(w=>w && typeof w.id==='string' && Array.isArray(w.exercises)) || !data.library.every(x=>x && typeof x.id==='string' && typeof x.name==='string')) throw Error('Damaged workout data');
  return backup;
}
async function importBackup(e){
  const file=e.target.files?.[0]; if(!file)return;
  if(!/json/i.test(file.type||'') && !/\.json$/i.test(file.name)){ return restoreError('Choose a JSON backup file.'); }
  try {
    const backup=validateBackup(JSON.parse(await readFile(file))); const data=backup.data;
    modal(`<h2>Restore backup?</h2><p><b>Backup date:</b> ${new Date(backup.exportedAt).toLocaleDateString()}<br><b>App version:</b> ${backup.applicationVersion||'1.0.0'}<br><b>Programs:</b> ${data.programs.length} · <b>Workouts:</b> ${data.workouts.length} · <b>Exercises:</b> ${data.library.length}</p><button class="primary wide" id="replace">Replace data</button><button class="secondary wide" id="merge">Merge data</button><button class="text-button" data-close>Cancel</button>`);
    $('#replace').onclick=()=>{state=data;save();closeModal();render()};
    $('#merge').onclick=()=>{state.workouts=[...state.workouts,...data.workouts.filter(x=>!state.workouts.some(y=>y.id===x.id))];state.programs=[...state.programs,...data.programs.filter(x=>!state.programs.some(y=>y.id===x.id))];state.library=[...state.library,...data.library.filter(x=>!state.library.some(y=>y.id===x.id))];state.body=[...state.body,...data.body.filter(x=>!state.body.some(y=>y.id===x.id))];save();closeModal();render()};
  } catch { restoreError('Choose a valid Form Training JSON backup with the required data.'); }
  e.target.value='';
}
function readFile(file){ if(file.text) return file.text(); return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsText(file);}); }
function restoreError(message){ modal(`<h2>That backup can’t be restored</h2><p>${message}</p><button class="primary wide" data-close>Close</button>`); }
function historyDetail(id){const w=state.workouts.find(x=>x.id===id);modal(`<div class="modal-head"><div><p class="eyebrow">${formatDate(w.date)} · ${duration(w)} MIN</p><h2>${w.name}</h2></div><button data-close>×</button></div><p>${kg(volume(w))} training volume · ${allSets(w).length} completed sets</p>${w.exercises.map(e=>`<div class="detail-ex"><b>${exName(e.exerciseId)}</b>${e.sets.filter(s=>s.completed).map(s=>`<span>${s.weight} kg × ${s.reps} <em>RIR ${s.rir}</em></span>`).join('')}</div>`).join('')}`)}
function editProgram(){const program=currentProgram();modal(`<h2>Edit program</h2><label>Program name<input id="program-name" value="${program.name}" maxlength="60"></label><label>Description<textarea id="program-description" maxlength="300">${program.description}</textarea></label><p>Workout exercises and set targets can be adjusted when you start a session, without changing prior history.</p><button class="primary wide" id="save-program">Save program</button>`);$('#save-program').onclick=()=>{const name=$('#program-name').value.trim(),description=$('#program-description').value.trim();if(!name)return;program.name=name;program.description=description;program.updatedAt=today();save();closeModal();render()}}
function bodyModal(){modal(`<h2>Body check-in</h2><label>Body weight (kg)<input id="body-weight" type="number" inputmode="decimal" placeholder="e.g. 82.4"></label><label>Body fat % (optional)<input id="body-fat" type="number" inputmode="decimal" placeholder="e.g. 15"></label><button class="primary wide" id="save-body">Save check-in</button>`);$('#save-body').onclick=()=>{const weight=+$('#body-weight').value;if(!weight)return;state.body.push({id:uid(),date:today(),weight,fat:$('#body-fat').value});save();closeModal();render()}}
window.addEventListener('beforeinstallprompt', event=>{event.preventDefault();deferredInstall=event;});
async function boot(){
  try {
    state=await store.read()||seed();
    if(!state.library)state=seed();
    await save();
  } catch (error) {
    // iOS can deny IndexedDB in restrictive/private contexts. Keep the UI usable and explain that data is temporary.
    storageIssue='This browser cannot access IndexedDB, so new data is temporary. Enable website data/storage, then reopen the app.';
    state=seed();
    console.warn('Local storage unavailable', error);
  }
  if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(error=>console.warn('Offline support unavailable',error));
  render();
}
boot();
